// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdrFPm9bb_OFu26X80hNRyUx694gR0tbU',
    appId: '1:221190906812:web:a3e02f62d8cef2f06881b9',
    messagingSenderId: '221190906812',
    projectId: 'shopapp-1a4cc',
    authDomain: 'shopapp-1a4cc.firebaseapp.com',
    databaseURL: 'https://shopapp-1a4cc-default-rtdb.firebaseio.com',
    storageBucket: 'shopapp-1a4cc.appspot.com',
    measurementId: 'G-LJ3QD9QTK9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjeAigfr0Xo0ZbyTK0LJUtqzCw6n2nzU4',
    appId: '1:221190906812:android:b6a15114b26e446f6881b9',
    messagingSenderId: '221190906812',
    projectId: 'shopapp-1a4cc',
    databaseURL: 'https://shopapp-1a4cc-default-rtdb.firebaseio.com',
    storageBucket: 'shopapp-1a4cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMzohQYGPgMCOvH6yxFWh9EgCvKLM7Ccc',
    appId: '1:221190906812:ios:8c58085f1632eda26881b9',
    messagingSenderId: '221190906812',
    projectId: 'shopapp-1a4cc',
    databaseURL: 'https://shopapp-1a4cc-default-rtdb.firebaseio.com',
    storageBucket: 'shopapp-1a4cc.appspot.com',
    iosBundleId: 'com.example.shop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMzohQYGPgMCOvH6yxFWh9EgCvKLM7Ccc',
    appId: '1:221190906812:ios:8c58085f1632eda26881b9',
    messagingSenderId: '221190906812',
    projectId: 'shopapp-1a4cc',
    databaseURL: 'https://shopapp-1a4cc-default-rtdb.firebaseio.com',
    storageBucket: 'shopapp-1a4cc.appspot.com',
    iosBundleId: 'com.example.shop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdrFPm9bb_OFu26X80hNRyUx694gR0tbU',
    appId: '1:221190906812:web:93ebe43dd5fafc186881b9',
    messagingSenderId: '221190906812',
    projectId: 'shopapp-1a4cc',
    authDomain: 'shopapp-1a4cc.firebaseapp.com',
    databaseURL: 'https://shopapp-1a4cc-default-rtdb.firebaseio.com',
    storageBucket: 'shopapp-1a4cc.appspot.com',
    measurementId: 'G-2NLM1QDFZ2',
  );
}
